spring:
  profiles: dev
  devtools:
    restart:
      enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/portal?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT+8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    initialize: true
    continue-on-error: true
    initialSize : 5
    minIdle : 5
    maxActive : 20
    maxWait : 60000
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : SELECT 1 FROM DUAL
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxPoolPreparedStatementPerConnectionSize : 20
    filters : stat,wall,log4j
    connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat : true

server:
    port: 8080
logging:
    level:
       root: debug
mybatis:
    config-location: classpath:mybatis-config.xml
    type-aliases-package: org.ack.cms.pojo
       
